const products = [
    {
        id: 1,
        title: "Jirafa",
        price: 15000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/aU8lQna.png",
    },
    {
        id: 2,
        title: "White rabbit",
        price: 12000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/7ogrjzx.png",
    },
    {
        id: 3,
        title: "Pinguino morado",
        price: 8000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/tZvTTC2.png",
    },
    {
        id: 4,
        title: "Zorrito",
        price: 15000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/wR1NT4x.png",
    },
    {
        id: 5,
        title: "Conejito rosa",
        price: 8000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/4BxTMug.png",
    },
    {
        id: 6,
        title: "Perrito",
        price: 12000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/ezSSt1Z.png",
    },
    {
        id: 7,
        title: "Bailarina de ballet",
        price: 15000,
        stock: 6,
        category: "personajes",
        imageUrl: "https://i.imgur.com/mSme4sN.png",
    },
    {
        id: 8,
        title: "Pinguino verde",
        price: 12000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/9j8RNQp.png",
    },
    {
        id: 9,
        title: "Piggy",
        price: 12000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/2kWOq2E.png",
    },
    {
        id: 10,
        title: "Pinguino azul",
        price: 10000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/a9FIuJP.png",
    },
    {
        id: 11,
        title: "Thor",
        price: 15000,
        stock: 6,
        category: "personajes",
        imageUrl: "https://i.imgur.com/3SiCmLO.png",
    },
    {
        id: 12,
        title: "Puppy",
        price: 8000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/mZ9rhjm.png",
    },
    {
        id: 13,
        title: "Unicornio",
        price: 10000,
        stock: 6,
        category: "fantasia",
        imageUrl: "https://i.imgur.com/e12Ioyf.png",
    },
    {
        id: 14,
        title: "Dino",
        price: 15000,
        stock: 6,
        category: "fantasia",
        imageUrl: "https://i.imgur.com/dM3LaR3.png",
    },
    {
        id: 15,
        title: "Pinguino rosa",
        price: 10000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/1dKJ0L1.png",
    },
    {
        id: 16,
        title: "Pusheen",
        price: 10000,
        stock: 6,
        category: "animales",
        imageUrl: "https://i.imgur.com/DApBBQT.png",
    },
]

export default products;