const products = [
    {
        id: 67781001,
        title: "Jirafa",
        price: 15000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/aU8lQna.png",
    },
    {
        id: 67781002,
        title: "White rabbit",
        price: 12000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/7ogrjzx.png",
    },
    {
        id: 67781003,
        title: "Pinguino morado",
        price: 8000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/tZvTTC2.png",
    },
    {
        id: 67781004,
        title: "Zorrito",
        price: 15000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/wR1NT4x.png",
    },
    {
        id: 67781005,
        title: "Conejito rosa",
        price: 8000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/4BxTMug.png",
    },
    {
        id: 67781006,
        title: "Perrito",
        price: 12000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/ezSSt1Z.png",
    },
    {
        id: 67781007,
        title: "Bailarina de ballet",
        price: 15000,
        stock: 6,
        Pedescription: "luche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "personajes",
        imageUrl: "https://i.imgur.com/mSme4sN.png",
    },
    {
        id: 67781008,
        title: "Pinguino verde",
        price: 12000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/9j8RNQp.png",
    },
    {
        id: 67781009,
        title: "Piggy",
        price: 12000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/2kWOq2E.png",
    },
    {
        id: 67781010,
        title: "Pinguino azul",
        price: 10000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/a9FIuJP.png",
    },
    {
        id: 67781011,
        title: "Thor",
        price: 15000,
        stock: 6,
        Pedescription: "luche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "personajes",
        imageUrl: "https://i.imgur.com/3SiCmLO.png",
    },
    {
        id: 67781012,
        title: "Puppy",
        price: 8000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/mZ9rhjm.png",
    },
    {
        id: 67781013,
        title: "Unicornio",
        price: 10000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "fantasia",
        imageUrl: "https://i.imgur.com/e12Ioyf.png",
    },
    {
        id: 67781014,
        title: "Dino",
        price: 15000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "fantasia",
        imageUrl: "https://i.imgur.com/dM3LaR3.png",
    },
    {
        id: 67781015,
        title: "Pinguino rosa",
        price: 10000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/1dKJ0L1.png",
    },
    {
        id: 67781016,
        title: "Pusheen",
        price: 10000,
        stock: 6,
        description: "Peluche amigurumi realizado de manera artesanal con lanas certificadas y material de relleno hipoalergénico. Una de las mejores opciones que tendrás para regalar debido a su nivel de detalle y personalización.",
        category: "animales",
        imageUrl: "https://i.imgur.com/DApBBQT.png",
    },
]

export default products;